version: "3.8"

services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development

    prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
