# Stage 1: Base Image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port on which the app will run
EXPOSE 3000

# Command to run the app in development mode
CMD ["npm", "run", "dev"]
